
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '14G1', '12GP', '12'' GENERAL PURPOSE' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '14R1', '12RF', '12'' REEFER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2200', '20GP', '"20'' GENERAL PURPOSE 8''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2201', '20H1', '20'' hanger container    Rack 1-tier-8''6"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2206', '20H2', '20'' hanger container    Rack 2-tier-8''6"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2207', '20H3', '20'' hanger container    Rack 3-tier-8''6"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2208', '20H4', '20'' hanger container    Rack 4-tier-8''6"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2209', '20HG', 'GP CONTAINER WITH HANGER BAR INSTALLED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2210', '20GP', '"20'' X8''6"" VENT CROSS-SECTION < 25CM2"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2211', '20VT', '20'' VENTILATED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2212', '20HG', 'GP CONTAINER WITH HANGER BAR INSTALLED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2213', '20VT', '20'' GP VENT AT LOWER & UPPER PARTS' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2215', '20VT', '20'' VENTILATED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2217', '20VT', '20'' VENTILATED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2219', '20HG', '"20'' GP WITH HANGER BAR - 8''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2220', '20IH', '20'' INSULATED & HEATED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2230', '20RF', '"20'' REEFER - 8''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2232', '20RF', '"20'' REEFER - 8''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2250', '20OT', '20'' OPEN TOP' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2251', '20OT', '20'' OT W;REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2252', '20OS', '20'' OT W;OPEN SIDE' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2253', '20OS', '20'''' OT W;OPEN SIDE' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2260', '20FL', '"20"" PLATFORM"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2261', '20FL', '20'' PLATFORM' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2262', '20FL', '"20"" PLATFORM"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2263', '20FL', '20'' FLATRACK - W;FOLD ENDS' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2264', '20FL', '"20"" PLATFORM"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2265', '20FL', '20'' FLATRACK - W;OPEN SIDE W;ROOF' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2270', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2271', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2272', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2273', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2274', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2275', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2276', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2278', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2279', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2290', '20AC', '20'' AIR CONTAINER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22A0', '20AC', '20'' AIR CONTAINER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22G0', '20GP', '"20'' GENERAL PURPOSE 8''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22G1', '20GP', '20'' X 8''6 GENERAL PURPOSE' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22G4', '20HG', 'GP CONTAINER WITH HANGER BAR INSTALLED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22G8', '20MU', '20'' GP with NITEC Mother Unit' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22G9', '20HG', '20'' GP WITH HANGER BAR' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22H5', '20IH', '20'' INSULATED & HEATED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22P0', '20FL', '"20"" PLATFORM"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22P1', '20FL', '20'' PLATFORM' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22P3', '20FL', '20'' FLATRACK - W;FOLD ENDS' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22P4', '20FL', '20'' FLATRACK - W;FOLD POSTS' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22P5', '20FL', '20'' FLATRACK - W;OPEN SIDE W;ROOF' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22R0', '20RF', '20'' REEFER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22R1', '20RF', '20'' REEFER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22R3', '20RF', '20'' REEFER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22T0', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22T1', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22T4', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22T5', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22T6', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22T8', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22T9', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22U0', '20OT', '20'' OPEN TOP' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22U1', '20OT', '20'' OT W;REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22U2', '20OS', '20'''' OT W;OPEN SIDE' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22V0', '20VT', '20'' GP VENT AT LOWER & UPPER PARTS' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '22V1', '20VT', '20'' VENTILATED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2300', '20GP', '20'' GP 8''6'''' WITH TUNNEL' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2332', '20RF', '20'' REEFER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2400', '20HQ', '"20'' X9''6"" GENERAL PURPOSE"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2410', '20HQ', '"20'' X9''6"" GENERAL PURPOSE"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2420', '20IH', '20'' INSULATED & HEATED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2430', '20RF', '20'' REEFER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2432', '20RQ', '"20'' REEFER -9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2450', '20OT', '20'' OPEN TOP' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2451', '20OT', '20'' HQ OT W;REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2460', '20FL', '20'' FLATRACK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2464', '20FL', '20'' FLATRACK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2465', '20FL', '20'' HQ FL W;OPEN SIDE W;ROOF' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2470', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2490', '20AC', '20'' HQ AIR CONTAINER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '24A0', '20AC', '20'' HQ AIR CONTAINER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '24G0', '20HQ', '"20'' X9''6"" GENERAL PURPOSE"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '24G1', '20HQ', '20'' HQ W;TUNNEL VENT SECTION <25CM2' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '24H5', '20IH', '20'' HQ ISULATED & HEATED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '24P0', '20FL', '20'' HQ FLATRACK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '24P2', '20FL', '20'' HQ FL W;OPEN SIDE W;ROOF' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '24P4', '20FL', '20''  HQ FLATRACK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '24R0', '20RQ', '"20'' REEFER -9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '24T0', '20TK', '20'' HQ TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '24U0', '20OT', '20'' HQ OPEN TOP' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '24U1', '20OT', '20'' HQ OT W;REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2500', '20HQ', '"20'' X9''6"" GENERAL PURPOSE"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2510', '20HQ', '20'' HQ W;TUNNEL VENT SECTION <25CM2' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2513', '20VT', '20'' VENTILATED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2532', '20RQ', '"20"" REEFER -9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2550', '20OT', '"20"" HQ OPEN TOP"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2551', '20OT', '"20"" HQ OT W;REMOVE TOP MEMBER"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2570', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '25G0', '20HQ', '"20'' X9''6"" GENERAL PURPOSE"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '25G1', '20HQ', '20'' HQ W;TUNNEL VENT SECTION <25CM2' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '25R1', '20RQ', '"20"" REEFER -9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '25T0', '20TK', '20'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '25U0', '20OT', '"20"" HQ OPEN TOP"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '25U1', '20OT', '"20"" HQ OT W;REMOVE TOP MEMBER"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '25V1', '20VT', '20'' VENTILATED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2650', '20HH', '20'' HALF HEIGHT OPEN TOP' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2651', '20HH', '20'' HH OP W;REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2659', '20HH', '20'' HH OT W;2 SIDES SLOT OPENING' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2700', '20XX', '20'' HH GP W;TUNNEL' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2732', '20XX', '20'' HH W;TUNNEL REEFER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2751', '20XX', '20'' HH OT W;TUNNEL & REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2760', '20XX', '20'' HH W;TUNNEL FLATRACK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2764', '20XX', '20'' HH W;TUNNEL FL W;FOLD POST' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2765', '20XX', '20'' HH W;TUNNEL FL W;OPEN SIDE W;ROOF' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2790', '20AC', '20'' HH W;TUNNEL AIR CONTAINER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2850', '20HH', '20'' HALF HEIGHT OPEN TOP' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2851', '20HH', '20'' HH OP W;REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '28A0', '20AC', '20'' HH W;TUNNEL AIR CONTAINER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '28G0', '20GP', '20'' HH GP W;TUNNEL' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '28P0', '20FL', '20'' HH W;TUNNEL FLATRACK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '28P2', '20FL', '20'' HH W;TUNNEL FL W;OPEN SIDE W;ROOF' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '28P4', '20FL', '20'' HH W;TUNNEL FL W;FOLD POST' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '28R3', '20RF', '20'' HH W;TUNNEL REEFER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '28U0', '20HH', '20'' HALF HEIGHT OPEN TOP' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '28U1', '20HH', '20'' HH OP W;REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '28U2', '20HH', '20'' HH OT W;2 SIDES SLOT OPENING' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2900', '20XX', '20'' GP =<4''' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2932', '20XX', '20'' REEFER =<4''' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2951', '20XX', '20'' OT W;REMOVE TOP MEMBER =<4''' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2960', '20PL', '20'' PLATFORM' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2964', '20PL', '20'' PL W;FOLD POST =<4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2965', '20PL', '20'' PL W;OPEN SIDE W;ROOF =<4''' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '2990', '20AC', '20'' AIR CONTAINER - =< 4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '29A0', '20AC', '20'' AIR CONTAINER - < 4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '29G0', '20MT', '20'' GENERAL PURPOSE 8''6' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '29P0', '20PL', '20'' PLATFORM <4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '29P2', '20PL', '20'' PL W;OPEN SIDE W;ROOF <4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '29P4', '20PL', '20'' PL W;FOLD POST <4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '29R3', '20RF', '20'' REEFER <4''' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '29U1', '20HH', '20'' HH OP W;REMOVE TOP MEMBER <4''' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '29U2', '20HH', '20'' HH OT W;2 SIDES SLOT OPENING <4''' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4200', '40GP', '40X 8''6GENERAL PURPOSE' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4201', '40H1', '40'' hanger container    Rack 1-tier-8''6"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4206', '40H2', '40'' hanger container    Rack 2-tier-8''6"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4207', '40H3', '40'' hanger container    Rack 3-tier-8''6"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4208', '40H4', '40'' hanger container    Rack 4-tier-8''6"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4209', '40HG', '40'' GENERAL PURPOSE WITH HANGER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4210', '40GX', '"40'' X 8''6"" VENT SECTION < 25CM2"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4220', '40IH', '40'' INSULATED & HEATED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4224', '40IH', '40'' INSULATED & HEATED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4230', '40RF', '"40'' REEFER 8''6"" WITHOUT TUNNEL"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4231', '40RF', '"40'' REEFER 8''6"" WITHOUT TUNNEL"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4232', '40RF', '"40'' REEFER 8''6"" WITHOUT TUNNEL"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4250', '40OT', '"40'' OPEN TOP 8''6""  WITHOUT TUNNEL"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4251', '40OT', '40'' OT W;REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4260', '40FL', '40'' FLATRACK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4261', '40FL', '40'' FL WITH FIXED END AND WITHOUT TUNNEL' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4264', '40FL', '40'' FLATRACK W;FOLD POST' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4265', '40FL', '40'' FL W;OPEN SIDE W;ROOF' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4270', '40TK', '40'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4290', '40HG', '40'' GENERAL PURPOSE WITH HANGER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42A0', '40AC', '40'' AIR CONTAINER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42G0', '40GP', '"40'' GENERAL PURPOSE 8''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42G1', '40GP', '40 X 8''6 GENERAL PURPOSE' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42G4', '40HG', '40'' GENERAL PURPOSE WITH HANGER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42G8', '40MU', '40'' GP with NITEC Mother Unit' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42G9', '40HG', '40'' GENERAL PURPOSE WITH HANGER BAR' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42H0', '40RF', '40'' REEFER (PORTHOLE INSULATED)' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42H5', '40IH', '40'' INSULATED & HEATED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42P0', '40FL', '40'' FLATRACK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42P1', '40FL', '40'' FL W;TUNNEL & FIXED END' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42P3', '40FL', '40'' FL W;TUNNEL & FOLD ENDS' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42P4', '40FL', '40'' FLATRACK W;FOLD POST' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42P5', '40FL', '40'' FL W;OPEN SIDE W;ROOF' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42R0', '40RF', '"40'' REEFER 8''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42R1', '40RF', '"40'' REEFER 8''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42T0', '40TK', '40'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42U0', '40OT', '"40'' OPEN TOP 8''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42U1', '40OT', '40'' OT W;REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '42V0', '40VT', '40''GP VENT AT LOWER & UPPER PARTS' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4300', '40GP', '"40'' GENERAL PURPOSE 8''6"" WITH TUNNEL"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4310', '40GP', '40'' GP W;TUNNEL VENT SECTION < 25CM2' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4311', '40VT', '40'' GP W;TUNNEL VENT SECTION >25CM2' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4312', '40HG', '40'' GENERAL PURPOSE WITH HANGER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4313', '40VT', '40''GP VENT AT LOWER & UPPER PARTS' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4315', '40VT', '40'' VENTILATED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4317', '40VT', '40'' VENTILATED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4319', '40HG', '40'' GENERAL PURPOSE WITH HANGER BAR' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4320', '40IH', '40'' INSULATED & HEATED' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4330', '40RF', '"40'' REEFER 8''6"" WITH TUNNEL"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4332', '40RF', '"40'' REEFER 8''6"" WITH TUNNEL"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4340', '40RF', '40'' REEFER (PORTHOLE INSULATED)' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4350', '40OT', '"40'' OPEN TOP 8''6"" WITH TUNNEL"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4351', '40OT', '40'' OT W;TUNNEL & REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4360', '40FL', '40'' FLATRACK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4361', '40FL', '40'' FL W;TUNNEL & FIXED END' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4362', '40FL', '40'' FLATRACK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4363', '40FL', '40'' FL W;TUNNEL & FOLD ENDS' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4364', '40FL', '40'' FL W;TUNNEL & FOLD POST' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4365', '40FL', '"40'' FL W;TUNNEL, OPEN SIDE W;ROOF"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4370', '40TK', '40'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4371', '40TK', '40'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4372', '40TK', '40'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4373', '40TK', '40'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4374', '40TK', '40'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4375', '40TK', '40'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4376', '40TK', '40'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4377', '40TK', '40'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4378', '40TK', '40'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4379', '40TK', '40'' TANK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4390', '40AC', '40'' AIR CONTAINER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4400', '40HX', '"40'' GP W;OUT TUNNEL - 9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4410', '40HX', '40'' HX VENT SECTION < 25CM2' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4430', '40RQ', '"40'' REEFER WITH HEIGHT > 8''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4432', '40RQ', '40'' HQ REEFER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4451', '40OT', '40'' HX OPEN TOP W;REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4460', '40FL', '40'' HX FLATRACK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4464', '40FL', '40'' HX FL W;FOLD POST' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4465', '40FL', '40'' HX FL W;OPEN SIDE W;ROOF' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4490', '40AC', '"40'' HX AIR CONTAINER - 9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '44G0', '40HX', '"40'' GP W;OUT TUNNEL - 9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '44G1', '40HX', '40'' HX VENT SECTION < 25CM2' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '44P0', '40FL', '40'' HX FLATRACK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '44P4', '40FL', '40'' HX FL W;FOLD POST' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '44U1', '40OT', '40'' HX OPEN TOP W;REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4500', '40HQ', '"40'' GP W;TUNNEL - 9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4501', '40G1', '40'' HQ hanger container Rack 1-tier-9''6"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4506', '40G2', '40'' HQ hanger container Rack 2-tier-9''6"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4507', '40G3', '40'' HQ hanger container Rack 3-tier-9''6"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4508', '40G4', '40'' HQ hanger container Rack 4-tier-9''6"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4510', '40HQ', '"40'' X9''6"" W;TUNNEL VENT SECTION < 25CM2"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4530', '40RQ', '"40'' HQ REEFER - 9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4531', '40RQ', '"40HQ REEFER - 9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4532', '40RQ', '"40 HQ REEFER - 9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4550', '40OT', '40'' HQ OPEN TOP' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4590', '40AC', '"40'' HX AIR CONTAINER - 9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '45A0', '40AC', '"40'' HQ AIR CONTAINER - 9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '45G0', '40HQ', '40'' X 9''6' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '45G1', '40HQ', '"40 X 9''6 , VENT<25CM2"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '45G4', '40GH', '40"Hi-Cube Hanger Container' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '45P0', '40FL', '40'' HQ FLATRACK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '45P1', '40FL', '40'' HIGH CUBE FLATRACK' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '45P4', '40FL', '40'' HQ FL W;FOLD POST' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '45P5', '40FL', '40'' HQ FL W;OPEN SIDE W;ROOF' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '45R0', '40RQ', '"40'' HQ REEFER - 9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '45R1', '40RQ', '"40 HQ REEFER - 9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '45U0', '40OT', '"40'' HQ OPEN TOP - 9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '45U1', '40OT', '40'' HQ OPEN TOP W;REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4650', '40HH', '40'' HALF HEIGHT OPEN TOP WITHOUT TUNNEL' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4700', '40XX', '40'' HH GP W;TUNNEL' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4732', '40XX', '40'' HALF HEIGHT W;TUNNEL REEFER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4750', '40HH', '40'' HALF HEIGHT OPEN TOP WITH TUNNEL' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4751', '40HH', '40 HH OT W;TUNNEL & REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4760', '40XX', '40'' HH FLATRACK W;TUNNEL' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4764', '40XX', '40'' HH FL W;TUNNEL & FOLD END' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4765', '40XX', '"40'' HH FL W;TUNNEL, OPEN SIDE W;ROOF"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4790', '40AC', '40'' HH W;TUNNER AIR CONTAINER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4850', '40HH', '40'' HALF HEIGHT OPEN TOP WITHOUT TUNNEL' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4871', '40HH', '40'' HH OT W;TUNNEL &  REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '48A0', '40AC', '40'' HH W;TUNNER AIR CONTAINER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '48G0', '40GP', '40'' HH GP W;TUNNEL' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '48P0', '40FL', '40'' HH FLATRACK W;TUNNEL' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '48P2', '40FL', '"40'' HH FL W;TUNNEL, OPEN SIDE W;ROOF"' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '48P4', '40FL', '40'' HH FL W;TUNNEL & FOLD END' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '48R3', '40HH', '40'' HALF HEIGHT W;TUNNEL REEFER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '48T1', '40HH', '40'' HH OT W;TUNNEL &  REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '48U0', '40HH', '40'' HALF HEIGHT OPEN TOP' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '48U1', '40HH', '40 HH OT W;TUNNEL & REMOVE TOP MEMBER' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4900', '40XX', '40'' GENERAL PURPOSE < 4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4932', '40XX', '40'' REEFER - < 4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4951', '40XX', '40'' OT W;REMOVE TOP MEMBER - =<4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4960', '40PL', '40'' PLATFORM' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4964', '40PL', '40'' PLATFORM W;FOLD POST' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4965', '40PL', '40'' PL W;OPEN SIDE W;ROOF' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '4990', '40AC', '40'' AIR CONTAINER - =< 4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '49A0', '40AC', '40'' HH W;TUNNER AIR CONTAINER < 4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '49G0', '40GP', '40'' GENERAL PURPOSE < 4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '49P0', '40PL', '40'' PLATFORM < 4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '49P2', '40PL', '40'' PL W;OPEN SIDE W;ROOF <4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '49P4', '40PL', '40'' PLATFORM W;FOLD POST < 4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '49R3', '40RF', '40'' REEFER - < 4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '49U0', '40OT', '40'' OT <4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '49U1', '40OT', '40'' OT W;REMOVE TOP MEMBER - <4'' HIGH' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '9000', '45GP', '"45'' GP W;TUNNEL (ALUM) -8''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '9010', '45GP', '"45'' GP W;TUNNEL VENT SECTION<25CM28''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '9300', '45GP', '"45'' GP W;TUNNEL (ALUM) -8''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '9310', '45GP', '"45'' GP W;TUNNEL VENT SECTION<25CM2 8''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '9400', '45HQ', '45'' HIGH CUBE' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '9500', '45HQ', '"45'' GP W;TUNNEL (ALUM) - 9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '9510', '45HQ', '"45'' GP W;TUNNEL VENT SECTION<25CM2 9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '9530', '45RQ', '45RQ' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( '9531', '45RQ', '45RQ' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( 'L2G0', '45GP', '"45'' GP W;TUNNEL (ALUM) -8''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( 'L2G1', '45GP', '"45'' GP W;TUNNEL VENT SECTION<25CM2 8''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( 'L2U0', '45OT', '45'' Open Top' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( 'L5G0', '45HQ', '45'' HIGH CUBE' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( 'L5G1', '45HQ', '"45'' GP W;TUNNEL VENT SECTION<25CM2 9''6"""' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( 'L5R0', '45RQ', '45RQ' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( 'L5R1', '45RQ', '45RQ' ) 
;
INSERT INTO dbeqp.CNTR_ISO_TYPE ( ISO_CDE, GROUP_CDE, DESCRIPTION ) 
		 VALUES ( 'L5U0', '45OT', '45'' Open Top' ) 
;
