


drop table if exists dbeqp.SUP_PAYMENT;

drop table if exists dbeqp.SUP_ACCOUNT;

drop table if exists dbeqp.SUP_ASSIGN;

drop table if exists dbeqp.SUP_CONTACT;

drop table if exists dbeqp.sup_transaction;

drop table if exists dbeqp.SUP_USER;



CREATE TABLE dbeqp.SUP_PAYMENT (
  SUP_PAYEMENT_id int(11) NOT NULL AUTO_INCREMENT,
  SUP_ACCOUNT_ID int(11) NOT NULL,
  PAYMENT_DATE datetime NOT NULL,
  PAYMENT_TYPE varchar(10) NOT NULL,
  CONTACT_ID int(11) NOT NULL,
  AMMOUNT double(11,4) NOT NULL,
  CURRENCY varchar(10) NOT NULL,
  CURRENCY_RATE double(11,4) NOT NULL,
  START_DATE datetime NOT NULL,
  END_DATE datetime NOT NULL,
  CREATE_DT datetime ,
  UPDATE_DT datetime ,
  PRIMARY KEY (SUP_PAYEMENT_id)
) ;


CREATE TABLE dbeqp.SUP_ACCOUNT (
  SUP_ACCOUNT_id int(11) NOT NULL AUTO_INCREMENT,
  ACT_HLDR_NAME varchar(50) NOT NULL DEFAULT '',
  ACT_HLDR_ADDR varchar(300) NOT NULL DEFAULT '',
  ACT_BRANCH varchar(50) NOT NULL DEFAULT '',
  ACT_NUM varchar(50) NOT NULL DEFAULT '',
  IFSC_CODE varchar(50) NOT NULL DEFAULT '',
  BANK_ADDR varchar(300) NOT NULL DEFAULT '',
  CREATE_DT datetime DEFAULT NULL,
  UPDATE_DT datetime DEFAULT NULL,
  PRIMARY KEY (SUP_ACCOUNT_id)
);
CREATE TABLE dbeqp.SUP_ASSIGN (
  SUP_ASSIGN_id int(11) NOT NULL AUTO_INCREMENT,
  TRAINER_ID int(11) NOT NULL,
  TRAINEE_ID int(11) NOT NULL,
  START_DT datetime NOT NULL,
  END_DT datetime NOT NULL,
  STATUS varchar(10) NOT NULL,
  SUPPORT_TYPE varchar(50) NOT NULL,
  CREATE_DT datetime DEFAULT NULL,
  UPDATE_DT datetime DEFAULT NULL,
  PRIMARY KEY (SUP_ASSIGN_id)
);

CREATE TABLE dbeqp.SUP_CONTACT (
  SUP_CONTACT_id int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(100) NOT NULL DEFAULT '',
  MOBILE_NO varchar(15) DEFAULT NULL,
  LOCATION varchar(200) DEFAULT NULL,
  GMAIL_ID varchar(50) DEFAULT NULL,
  SKYPE_ID varchar(50) DEFAULT '',
  TUPE_OF_MEM varchar(50) NOT NULL DEFAULT '',
  JOIN_DT datetime DEFAULT NULL,
  CREATE_DT datetime DEFAULT NULL,
  UPDATE_DT datetime DEFAULT NULL,
  PRIMARY KEY (SUP_CONTACT_id)
);

      
 CREATE TABLE `dbeqp`.`sup_transaction` (
	`SUP_TRANSACTION_id` INT(11) NOT NULL AUTO_INCREMENT,
	`SUP_ACCOUNT_ID` INT(11) NOT NULL,
	`AMOUNT` VARCHAR(300) NOT NULL DEFAULT '',
	`OPERATION` VARCHAR(50) NOT NULL DEFAULT '',
	`CREATE_DT` DATETIME NULL DEFAULT NULL,
	`UPDATE_DT` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`SUP_TRANSACTION_id`)
);

CREATE  TABLE `dbeqp`.`SUP_USER` (
  `SUP_USER_ID` INT NOT NULL AUTO_INCREMENT ,
  `SUP_USER_NAME` VARCHAR(45) NOT NULL ,
  `SUP_USER_PWD` VARCHAR(45) NOT NULL ,
  `ENABLED` VARCHAR(45) NOT NULL,
  `ACT_NON_EXP` VARCHAR(45) NOT NULL,
  `CREDENTIALS_NON_EXP` VARCHAR(45) NOT NULL,
  `ACT_NON_LOCKED` VARCHAR(45) NOT NULL,
  `CREATE_DT` DATETIME NULL ,
  `UPDATE_DT` VARCHAR(45) NULL ,
  PRIMARY KEY (`SUP_USER_ID`) );

